//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Divuvina.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_LayThongTinXeChuaSapLich_Result> sp_LayThongTinXeChuaSapLich(Nullable<int> hangSanXuatXeKey, Nullable<int> loaiXeKey, string bangSoXe, string soSan, Nullable<System.DateTime> ngayCapPhep)
        {
            var hangSanXuatXeKeyParameter = hangSanXuatXeKey.HasValue ?
                new ObjectParameter("HangSanXuatXeKey", hangSanXuatXeKey) :
                new ObjectParameter("HangSanXuatXeKey", typeof(int));
    
            var loaiXeKeyParameter = loaiXeKey.HasValue ?
                new ObjectParameter("LoaiXeKey", loaiXeKey) :
                new ObjectParameter("LoaiXeKey", typeof(int));
    
            var bangSoXeParameter = bangSoXe != null ?
                new ObjectParameter("BangSoXe", bangSoXe) :
                new ObjectParameter("BangSoXe", typeof(string));
    
            var soSanParameter = soSan != null ?
                new ObjectParameter("SoSan", soSan) :
                new ObjectParameter("SoSan", typeof(string));
    
            var ngayCapPhepParameter = ngayCapPhep.HasValue ?
                new ObjectParameter("NgayCapPhep", ngayCapPhep) :
                new ObjectParameter("NgayCapPhep", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinXeChuaSapLich_Result>("sp_LayThongTinXeChuaSapLich", hangSanXuatXeKeyParameter, loaiXeKeyParameter, bangSoXeParameter, soSanParameter, ngayCapPhepParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spTest(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spTest", keyParameter);
        }
    
        public virtual int sp_LuuThongTinSapLichBaoTriXe(string listXeKeyXML, Nullable<int> noiSuaChuaXeKey, Nullable<System.DateTime> ngaySapLich, Nullable<int> nhanVienSapLichKey, string ghiChu, ObjectParameter listXeKeyFailed)
        {
            var listXeKeyXMLParameter = listXeKeyXML != null ?
                new ObjectParameter("ListXeKeyXML", listXeKeyXML) :
                new ObjectParameter("ListXeKeyXML", typeof(string));
    
            var noiSuaChuaXeKeyParameter = noiSuaChuaXeKey.HasValue ?
                new ObjectParameter("NoiSuaChuaXeKey", noiSuaChuaXeKey) :
                new ObjectParameter("NoiSuaChuaXeKey", typeof(int));
    
            var ngaySapLichParameter = ngaySapLich.HasValue ?
                new ObjectParameter("NgaySapLich", ngaySapLich) :
                new ObjectParameter("NgaySapLich", typeof(System.DateTime));
    
            var nhanVienSapLichKeyParameter = nhanVienSapLichKey.HasValue ?
                new ObjectParameter("NhanVienSapLichKey", nhanVienSapLichKey) :
                new ObjectParameter("NhanVienSapLichKey", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LuuThongTinSapLichBaoTriXe", listXeKeyXMLParameter, noiSuaChuaXeKeyParameter, ngaySapLichParameter, nhanVienSapLichKeyParameter, ghiChuParameter, listXeKeyFailed);
        }
    
        public virtual ObjectResult<sp_LayThongTinXeDaSapLich_Result> sp_LayThongTinXeDaSapLich()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinXeDaSapLich_Result>("sp_LayThongTinXeDaSapLich");
        }
    }
}
